trigger:
  branches:
    include:
      - '*'
    exclude:
      - adf_publish

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: github-mirror

steps:
  - checkout: self
    fetchDepth: 0
    persistCredentials: true

  - script:  |
      git remote add github https://chebeno:${GITHUB_PAT}@github.com/chebeno/fifa-worldcup-data-platform.git
      git push github --all --force
      git push github --tags --force
    displayName: 'Mirror vers GitHub'
    env:
      GITHUB_PAT: $(GITHUB_PAT)